apiVersion: v1
kind: ConfigMap
metadata:
  name: file-service-config
data:
  STORAGE_DIR: /app/uploads
  MONGO_USER: root
  MONGO_HOST: mongodb-container
  MONGO_PORT: "27017"
  DOWNLOAD-PREFIX: api.harinemedu.vn
  DOWNLOAD-PORT: "80"
