apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: book-review
spec:
  selector:
    app: file-service-pod
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
  type: ClusterIP