apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-service-pvc
  namespace: book-review
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-storage
