apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: book-review
spec:
  selector:
    app: profile-service-pod
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
