alertmanager:
  config:
    global:
      resolve_timeout: 2m

    route:
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 1h
      receiver: slack-notifications
      routes:
        - matchers:
            - severity = "critical"
          receiver: slack-notifications

    receivers:
      - name: slack-notifications
        slack_configs:
          - api_url: ''
            channel: '#book-review-alerts'
            send_resolved: true
            title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
            text: |
              *Summary:* {{ .CommonAnnotations.summary }}
              *Description:* {{ .CommonAnnotations.description }}
              *Instance:* {{ .CommonLabels.instance }}
              *Severity:* {{ .CommonLabels.severity }}

    inhibit_rules:
      - source_matchers:
          - severity = "critical"
        target_matchers:
          - severity =~ "warning|info"
        equal: ['namespace', 'alertname']
      - source_matchers:
          - severity = "warning"
        target_matchers:
          - severity = "info"
        equal: ['namespace', 'alertname']
      - source_matchers:
          - alertname = "InfoInhibitor"
        target_matchers:
          - severity = "info"
        equal: ['namespace']
      - target_matchers:
          - alertname = "InfoInhibitor"

