apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway-pod
  ports:
    - protocol: TCP
      port: 80              # Cổng mà Ingress sẽ dùng
      targetPort: 8888
  type: ClusterIP

