apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: book-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-pod
  template:
    metadata:
      labels:
        app: api-gateway-pod
    spec:
      containers:
        - name: api-gateway
          image: registry.harinemdevops.online/book-reviews/api-gateway:develop-df89c08
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: api-gateway-config
      imagePullSecrets:
        - name: harbor-secret
