apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: book-review
spec:
  selector:
    app: identity-service-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP