apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
  namespace: book-review
data:
  MYSQL_HOST: mysql-container
  MYSQL_PORT: "3306"
  MYSQL_DB_NAME: identity_service
  MYSQL_USER: root
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  PROFILE_HOST: profile-service
  PROFILE_PORT: "8081"
