apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service-pod
  template:
    metadata:
      labels:
        app: identity-service-pod
    spec:
      containers:
      - name: identity-service
        image: nnhainam/identity-service-img:v1
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: MYSQL_PORT
        - name: MYSQL_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: MYSQL_DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: identity-secret
              key: MYSQL_PASSWORD
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: PROFILE_HOST
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: PROFILE_HOST
        - name: PROFILE_PORT
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: PROFILE_PORT
