apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: book-review
spec:
  selector:
    app: notification-service-pod
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
