apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-service-book-review
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/v4224/Book-Reviews-gitops.git
    targetRevision: develop
    path: app/file-service
  destination: 
    server: https://kubernetes.default.svc
    namespace: book-review

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

