apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: book-review
spec:
  selector:
    app: post-service-pod
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP
